import Testing
@testable import QueryCraftFeature
@testable import QueryCraftPostgreSQLDriver

struct PostgreSQLSchemaEditingProviderTests {
    private let provider = PostgreSQLSchemaEditingProvider(
        capabilities: PostgreSQLCapabilities(serverVersion: 170_000)
    )

    @Test
    func exposesPostgreSQL17SchemaEditingCapabilities() {
        let descriptor = provider.descriptor

        #expect(descriptor.defaultColumnType == "text")
        #expect(descriptor.columnTypes.contains("uuid"))
        #expect(descriptor.indexMethods == [
            "btree", "hash", "gist", "spgist", "gin", "brin",
        ])
        #expect(descriptor.automaticValueStyle == .identity)
        #expect(descriptor.generatedStorages == [.none, .stored])
        #expect(!descriptor.includesColumn(.characterSet))
        #expect(!descriptor.includesColumn(.collation))
        #expect(!descriptor.includesIndex(.visible))
        #expect(!descriptor.supportsTableOptions)
        #expect(!descriptor.supportsColumnVisibility)
        #expect(!descriptor.supportsOnUpdateExpression)
        #expect(!descriptor.supportsAlteringGeneratedColumns)
        #expect(!descriptor.supportsIndexPrefixLength)
        #expect(descriptor.supportsIndexDirection)
    }

    @Test
    func indexMethodCaseDoesNotCreateAPendingSchemaChange() throws {
        let index = WorkspaceDatabaseIndex(
            name: "events_created_at_idx",
            columns: [
                WorkspaceDatabaseIndexColumn(
                    sequence: 1,
                    name: "created_at",
                    prefixLength: nil,
                    direction: "A",
                    isExpression: false
                ),
            ],
            isUnique: false,
            isPrimary: false,
            type: "BTREE",
            cardinality: nil,
            isVisible: true,
            comment: ""
        )
        var editor = WorkspaceDatabaseSchemaEditorState()
        editor.loadIndexesIfNeeded([index])
        let item = try #require(editor.indexes.first)
        var definition = item.definition
        definition.method = "btree"
        editor.updateIndex(id: item.id, definition: definition)

        #expect(!editor.hasChanges)
    }

    @Test
    func createsPostgreSQLTableWithIdentityCommentsAndNamedPrimaryKey() throws {
        var editor = WorkspaceDatabaseSchemaEditorState()
        let id = editor.addColumn(defaultType: "integer")
        var idDefinition = try #require(
            editor.columns.first(where: { $0.id == id })?.definition
        )
        idDefinition.name = "id"
        idDefinition.isNullable = false
        idDefinition.defaultMode = .none
        idDefinition.isAutoIncrement = true
        idDefinition.comment = "row id"
        editor.updateColumn(id: id, definition: idDefinition)
        editor.setPrimaryKey(columnID: id, isEnabled: true)

        let label = editor.addColumn(defaultType: "text")
        var labelDefinition = try #require(
            editor.columns.first(where: { $0.id == label })?.definition
        )
        labelDefinition.name = "label"
        labelDefinition.defaultMode = .value
        labelDefinition.defaultValue = "pending"
        editor.updateColumn(id: label, definition: labelDefinition)

        let plan = try provider.makeExecutionPlan(
            for: .create(
                databaseName: "app",
                tableName: "events",
                columns: editor.columns,
                indexes: editor.indexes
            )
        )

        #expect(plan.transactionMode == .transaction)
        #expect(plan.statements.map(\.sql) == [
            "CREATE TABLE \"public\".\"events\" (\"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, \"label\" text DEFAULT 'pending')",
            "COMMENT ON COLUMN \"public\".\"events\".\"id\" IS 'row id'",
            "ALTER TABLE \"public\".\"events\" ADD CONSTRAINT \"events_pkey\" PRIMARY KEY (\"id\")",
        ])
        #expect(
            WorkspaceSQLPreviewStatement.make(schemaExecutionPlan: plan)
                .map(\.sql)
                == plan.statements.map { $0.sql + ";" }
        )
    }

    @Test
    func createsTableInSelectedSchema() throws {
        var editor = WorkspaceDatabaseSchemaEditorState()
        let id = editor.addColumn(defaultType: "integer")
        var definition = try #require(
            editor.columns.first(where: { $0.id == id })?.definition
        )
        definition.name = "id"
        editor.updateColumn(id: id, definition: definition)

        let plan = provider.makeExecutionPlan(
            for: .create(
                databaseName: "app",
                tableName: "audit.events",
                columns: editor.columns,
                indexes: []
            )
        )

        #expect(
            plan.statements.first?.sql
                == "CREATE TABLE \"audit\".\"events\" (\"id\" integer DEFAULT NULL)"
        )
    }

    @Test
    func refusesUnsupportedGeneratedColumnExpressionAlteration() {
        let original = WorkspaceDatabaseColumn(
            name: "total",
            type: "integer",
            collation: nil,
            isNullable: true,
            key: "",
            defaultValue: nil,
            extra: "STORED GENERATED",
            comment: "",
            generationExpression: "price * quantity"
        )
        var item = WorkspaceDatabaseSchemaEditorState.ColumnItem(column: original)
        item.definition.generationExpression = "price * quantity * 2"
        let changes = WorkspaceDatabaseSchemaChangeSet(
            selection: WorkspaceDatabaseObjectSelection(
                databaseName: "app",
                objectName: "public.orders",
                kind: .table
            ),
            columns: [item],
            indexes: []
        )

        #expect(throws: (any Error).self) {
            _ = try provider.makeExecutionPlan(for: changes)
        }
    }
}
