enum SQLStaticCatalog {
    // MySQL 5.7, 8.0, and 8.4 keyword union. Keep this lexical catalog
    // independent from parser coverage: context changes ranking, never visibility.
    // Sources: https://dev.mysql.com/doc/refman/{5.7,8.0,8.4}/en/keywords.html
    static let mysqlKeywords = [
        "ACCESSIBLE", "ACCOUNT", "ACTION", "ACTIVE", "ADD", "ADMIN", "AFTER", "AGAINST",
        "AGGREGATE", "ALGORITHM", "ALL", "ALTER", "ALWAYS", "ANALYSE", "ANALYZE", "AND", "ANY",
        "ARRAY", "AS", "ASC", "ASCII", "ASENSITIVE", "AT", "ATTRIBUTE", "AUTHENTICATION",
        "AUTO", "AUTOEXTEND_SIZE", "AUTO_INCREMENT", "AVG", "AVG_ROW_LENGTH", "BACKUP",
        "BEFORE", "BEGIN", "BERNOULLI", "BETWEEN", "BIGINT", "BINARY", "BINLOG", "BIT", "BLOB",
        "BLOCK", "BOOL", "BOOLEAN", "BOTH", "BTREE", "BUCKETS", "BULK", "BY", "BYTE", "CACHE",
        "CALL", "CASCADE", "CASCADED", "CASE", "CATALOG_NAME", "CHAIN", "CHALLENGE_RESPONSE",
        "CHANGE", "CHANGED", "CHANNEL", "CHAR", "CHARACTER", "CHARSET", "CHECK", "CHECKSUM",
        "CIPHER", "CLASS_ORIGIN", "CLIENT", "CLONE", "CLOSE", "COALESCE", "CODE", "COLLATE",
        "COLLATION", "COLUMN", "COLUMNS", "COLUMN_FORMAT", "COLUMN_NAME", "COMMENT", "COMMIT",
        "COMMITTED", "COMPACT", "COMPLETION", "COMPONENT", "COMPRESSED", "COMPRESSION",
        "CONCURRENT", "CONDITION", "CONNECTION", "CONSISTENT", "CONSTRAINT",
        "CONSTRAINT_CATALOG", "CONSTRAINT_NAME", "CONSTRAINT_SCHEMA", "CONTAINS", "CONTEXT",
        "CONTINUE", "CONVERT", "CPU", "CREATE", "CROSS", "CUBE", "CUME_DIST", "CURRENT",
        "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER", "CURSOR",
        "CURSOR_NAME", "DATA", "DATABASE", "DATABASES", "DATAFILE", "DATE", "DATETIME", "DAY",
        "DAY_HOUR", "DAY_MICROSECOND", "DAY_MINUTE", "DAY_SECOND", "DEALLOCATE", "DEC",
        "DECIMAL", "DECLARE", "DEFAULT", "DEFAULT_AUTH", "DEFINER", "DEFINITION", "DELAYED",
        "DELAY_KEY_WRITE", "DELETE", "DENSE_RANK", "DESC", "DESCRIBE", "DESCRIPTION",
        "DES_KEY_FILE", "DETERMINISTIC", "DIAGNOSTICS", "DIRECTORY", "DISABLE", "DISCARD",
        "DISK", "DISTINCT", "DISTINCTROW", "DIV", "DO", "DOUBLE", "DROP", "DUAL", "DUMPFILE",
        "DUPLICATE", "DYNAMIC", "EACH", "ELSE", "ELSEIF", "EMPTY", "ENABLE", "ENCLOSED",
        "ENCRYPTION", "END", "ENDS", "ENFORCED", "ENGINE", "ENGINES", "ENGINE_ATTRIBUTE",
        "ENUM", "ERROR", "ERRORS", "ESCAPE", "ESCAPED", "EVENT", "EVENTS", "EVERY", "EXCEPT",
        "EXCHANGE", "EXCLUDE", "EXECUTE", "EXISTS", "EXIT", "EXPANSION", "EXPIRE", "EXPLAIN",
        "EXPORT", "EXTENDED", "EXTENT_SIZE", "FACTOR", "FAILED_LOGIN_ATTEMPTS", "FALSE",
        "FAST", "FAULTS", "FETCH", "FIELDS", "FILE", "FILE_BLOCK_SIZE", "FILTER", "FINISH",
        "FIRST", "FIRST_VALUE", "FIXED", "FLOAT", "FLOAT4", "FLOAT8", "FLUSH", "FOLLOWING",
        "FOLLOWS", "FOR", "FORCE", "FOREIGN", "FORMAT", "FOUND", "FROM", "FULL", "FULLTEXT",
        "FUNCTION", "GENERAL", "GENERATE", "GENERATED", "GEOMCOLLECTION", "GEOMETRY",
        "GEOMETRYCOLLECTION", "GET", "GET_FORMAT", "GET_MASTER_PUBLIC_KEY",
        "GET_SOURCE_PUBLIC_KEY", "GLOBAL", "GRANT", "GRANTS", "GROUP", "GROUPING", "GROUPS",
        "GROUP_REPLICATION", "GTIDS", "GTID_ONLY", "HANDLER", "HASH", "HAVING", "HELP",
        "HIGH_PRIORITY", "HISTOGRAM", "HISTORY", "HOST", "HOSTS", "HOUR", "HOUR_MICROSECOND",
        "HOUR_MINUTE", "HOUR_SECOND", "IDENTIFIED", "IF", "IGNORE", "IGNORE_SERVER_IDS",
        "IMPORT", "IN", "INACTIVE", "INDEX", "INDEXES", "INFILE", "INITIAL", "INITIAL_SIZE",
        "INITIATE", "INNER", "INOUT", "INSENSITIVE", "INSERT", "INSERT_METHOD", "INSTALL",
        "INSTANCE", "INT", "INT1", "INT2", "INT3", "INT4", "INT8", "INTEGER", "INTERSECT",
        "INTERVAL", "INTO", "INVISIBLE", "INVOKER", "IO", "IO_AFTER_GTIDS", "IO_BEFORE_GTIDS",
        "IO_THREAD", "IPC", "IS", "ISOLATION", "ISSUER", "ITERATE", "JOIN", "JSON",
        "JSON_TABLE", "JSON_VALUE", "KEY", "KEYRING", "KEYS", "KEY_BLOCK_SIZE", "KILL", "LAG",
        "LANGUAGE", "LAST", "LAST_VALUE", "LATERAL", "LEAD", "LEADING", "LEAVE", "LEAVES",
        "LEFT", "LESS", "LEVEL", "LIKE", "LIMIT", "LINEAR", "LINES", "LINESTRING", "LIST",
        "LOAD", "LOCAL", "LOCALTIME", "LOCALTIMESTAMP", "LOCK", "LOCKED", "LOCKS", "LOG",
        "LOGFILE", "LOGS", "LONG", "LONGBLOB", "LONGTEXT", "LOOP", "LOW_PRIORITY", "MANUAL",
        "MASTER", "MASTER_AUTO_POSITION", "MASTER_BIND", "MASTER_COMPRESSION_ALGORITHMS",
        "MASTER_CONNECT_RETRY", "MASTER_DELAY", "MASTER_HEARTBEAT_PERIOD", "MASTER_HOST",
        "MASTER_LOG_FILE", "MASTER_LOG_POS", "MASTER_PASSWORD", "MASTER_PORT",
        "MASTER_PUBLIC_KEY_PATH", "MASTER_RETRY_COUNT", "MASTER_SERVER_ID", "MASTER_SSL",
        "MASTER_SSL_CA", "MASTER_SSL_CAPATH", "MASTER_SSL_CERT", "MASTER_SSL_CIPHER",
        "MASTER_SSL_CRL", "MASTER_SSL_CRLPATH", "MASTER_SSL_KEY",
        "MASTER_SSL_VERIFY_SERVER_CERT", "MASTER_TLS_CIPHERSUITES", "MASTER_TLS_VERSION",
        "MASTER_USER", "MASTER_ZSTD_COMPRESSION_LEVEL", "MATCH", "MAXVALUE",
        "MAX_CONNECTIONS_PER_HOUR", "MAX_QUERIES_PER_HOUR", "MAX_ROWS", "MAX_SIZE",
        "MAX_UPDATES_PER_HOUR", "MAX_USER_CONNECTIONS", "MEDIUM", "MEDIUMBLOB", "MEDIUMINT",
        "MEDIUMTEXT", "MEMBER", "MEMORY", "MERGE", "MESSAGE_TEXT", "MICROSECOND", "MIDDLEINT",
        "MIGRATE", "MINUTE", "MINUTE_MICROSECOND", "MINUTE_SECOND", "MIN_ROWS", "MOD", "MODE",
        "MODIFIES", "MODIFY", "MONTH", "MULTILINESTRING", "MULTIPOINT", "MULTIPOLYGON",
        "MUTEX", "MYSQL_ERRNO", "NAME", "NAMES", "NATIONAL", "NATURAL", "NCHAR", "NDB",
        "NDBCLUSTER", "NESTED", "NETWORK_NAMESPACE", "NEVER", "NEW", "NEXT", "NO", "NODEGROUP",
        "NONE", "NOT", "NOWAIT", "NO_WAIT", "NO_WRITE_TO_BINLOG", "NTH_VALUE", "NTILE", "NULL",
        "NULLS", "NUMBER", "NUMERIC", "NVARCHAR", "OF", "OFF", "OFFSET", "OJ", "OLD",
        "OLD_PASSWORD", "ON", "ONE", "ONLY", "OPEN", "OPTIMIZE", "OPTIMIZER_COSTS", "OPTION",
        "OPTIONAL", "OPTIONALLY", "OPTIONS", "OR", "ORDER", "ORDINALITY", "ORGANIZATION",
        "OTHERS", "OUT", "OUTER", "OUTFILE", "OVER", "OWNER", "PACK_KEYS", "PAGE", "PARALLEL",
        "PARSER", "PARSE_GCOL_EXPR", "PARSE_TREE", "PARTIAL", "PARTITION", "PARTITIONING",
        "PARTITIONS", "PASSWORD", "PASSWORD_LOCK_TIME", "PATH", "PERCENT_RANK", "PERSIST",
        "PERSIST_ONLY", "PHASE", "PLUGIN", "PLUGINS", "PLUGIN_DIR", "POINT", "POLYGON", "PORT",
        "PRECEDES", "PRECEDING", "PRECISION", "PREPARE", "PRESERVE", "PREV", "PRIMARY",
        "PRIVILEGES", "PRIVILEGE_CHECKS_USER", "PROCEDURE", "PROCESS", "PROCESSLIST",
        "PROFILE", "PROFILES", "PROXY", "PURGE", "QUALIFY", "QUARTER", "QUERY", "QUICK",
        "RANDOM", "RANGE", "RANK", "READ", "READS", "READ_ONLY", "READ_WRITE", "REAL",
        "REBUILD", "RECOVER", "RECURSIVE", "REDOFILE", "REDO_BUFFER_SIZE", "REDUNDANT",
        "REFERENCE", "REFERENCES", "REGEXP", "REGISTRATION", "RELAY", "RELAYLOG",
        "RELAY_LOG_FILE", "RELAY_LOG_POS", "RELAY_THREAD", "RELEASE", "RELOAD", "REMOVE",
        "RENAME", "REORGANIZE", "REPAIR", "REPEAT", "REPEATABLE", "REPLACE", "REPLICA",
        "REPLICAS", "REPLICATE_DO_DB", "REPLICATE_DO_TABLE", "REPLICATE_IGNORE_DB",
        "REPLICATE_IGNORE_TABLE", "REPLICATE_REWRITE_DB", "REPLICATE_WILD_DO_TABLE",
        "REPLICATE_WILD_IGNORE_TABLE", "REPLICATION", "REQUIRE", "REQUIRE_ROW_FORMAT", "RESET",
        "RESIGNAL", "RESOURCE", "RESPECT", "RESTART", "RESTORE", "RESTRICT", "RESUME",
        "RETAIN", "RETURN", "RETURNED_SQLSTATE", "RETURNING", "RETURNS", "REUSE", "REVERSE",
        "REVOKE", "RIGHT", "RLIKE", "ROLE", "ROLLBACK", "ROLLUP", "ROTATE", "ROUTINE", "ROW",
        "ROWS", "ROW_COUNT", "ROW_FORMAT", "ROW_NUMBER", "RTREE", "S3", "SAVEPOINT",
        "SCHEDULE", "SCHEMA", "SCHEMAS", "SCHEMA_NAME", "SECOND", "SECONDARY",
        "SECONDARY_ENGINE", "SECONDARY_ENGINE_ATTRIBUTE", "SECONDARY_LOAD", "SECONDARY_UNLOAD",
        "SECOND_MICROSECOND", "SECURITY", "SELECT", "SENSITIVE", "SEPARATOR", "SERIAL",
        "SERIALIZABLE", "SERVER", "SESSION", "SET", "SHARE", "SHOW", "SHUTDOWN", "SIGNAL",
        "SIGNED", "SIMPLE", "SKIP", "SLAVE", "SLOW", "SMALLINT", "SNAPSHOT", "SOCKET", "SOME",
        "SONAME", "SOUNDS", "SOURCE", "SOURCE_AUTO_POSITION", "SOURCE_BIND",
        "SOURCE_COMPRESSION_ALGORITHMS", "SOURCE_CONNECT_RETRY", "SOURCE_DELAY",
        "SOURCE_HEARTBEAT_PERIOD", "SOURCE_HOST", "SOURCE_LOG_FILE", "SOURCE_LOG_POS",
        "SOURCE_PASSWORD", "SOURCE_PORT", "SOURCE_PUBLIC_KEY_PATH", "SOURCE_RETRY_COUNT",
        "SOURCE_SSL", "SOURCE_SSL_CA", "SOURCE_SSL_CAPATH", "SOURCE_SSL_CERT",
        "SOURCE_SSL_CIPHER", "SOURCE_SSL_CRL", "SOURCE_SSL_CRLPATH", "SOURCE_SSL_KEY",
        "SOURCE_SSL_VERIFY_SERVER_CERT", "SOURCE_TLS_CIPHERSUITES", "SOURCE_TLS_VERSION",
        "SOURCE_USER", "SOURCE_ZSTD_COMPRESSION_LEVEL", "SPATIAL", "SPECIFIC", "SQL",
        "SQLEXCEPTION", "SQLSTATE", "SQLWARNING", "SQL_AFTER_GTIDS", "SQL_AFTER_MTS_GAPS",
        "SQL_BEFORE_GTIDS", "SQL_BIG_RESULT", "SQL_BUFFER_RESULT", "SQL_CACHE",
        "SQL_CALC_FOUND_ROWS", "SQL_NO_CACHE", "SQL_SMALL_RESULT", "SQL_THREAD", "SQL_TSI_DAY",
        "SQL_TSI_HOUR", "SQL_TSI_MINUTE", "SQL_TSI_MONTH", "SQL_TSI_QUARTER", "SQL_TSI_SECOND",
        "SQL_TSI_WEEK", "SQL_TSI_YEAR", "SRID", "SSL", "STACKED", "START", "STARTING",
        "STARTS", "STATS_AUTO_RECALC", "STATS_PERSISTENT", "STATS_SAMPLE_PAGES", "STATUS",
        "STOP", "STORAGE", "STORED", "STRAIGHT_JOIN", "STREAM", "STRING", "SUBCLASS_ORIGIN",
        "SUBJECT", "SUBPARTITION", "SUBPARTITIONS", "SUPER", "SUSPEND", "SWAPS", "SWITCHES",
        "SYSTEM", "TABLE", "TABLES", "TABLESAMPLE", "TABLESPACE", "TABLE_CHECKSUM",
        "TABLE_NAME", "TEMPORARY", "TEMPTABLE", "TERMINATED", "TEXT", "THAN", "THEN",
        "THREAD_PRIORITY", "TIES", "TIME", "TIMESTAMP", "TIMESTAMPADD", "TIMESTAMPDIFF",
        "TINYBLOB", "TINYINT", "TINYTEXT", "TLS", "TO", "TRAILING", "TRANSACTION", "TRIGGER",
        "TRIGGERS", "TRUE", "TRUNCATE", "TYPE", "TYPES", "UNBOUNDED", "UNCOMMITTED",
        "UNDEFINED", "UNDO", "UNDOFILE", "UNDO_BUFFER_SIZE", "UNICODE", "UNINSTALL", "UNION",
        "UNIQUE", "UNKNOWN", "UNLOCK", "UNREGISTER", "UNSIGNED", "UNTIL", "UPDATE", "UPGRADE",
        "URL", "USAGE", "USE", "USER", "USER_RESOURCES", "USE_FRM", "USING", "UTC_DATE",
        "UTC_TIME", "UTC_TIMESTAMP", "VALIDATION", "VALUE", "VALUES", "VARBINARY", "VARCHAR",
        "VARCHARACTER", "VARIABLES", "VARYING", "VCPU", "VIEW", "VIRTUAL", "VISIBLE", "WAIT",
        "WARNINGS", "WEEK", "WEIGHT_STRING", "WHEN", "WHERE", "WHILE", "WINDOW", "WITH",
        "WITHOUT", "WORK", "WRAPPER", "WRITE", "X509", "XA", "XID", "XML", "XOR", "YEAR",
        "YEAR_MONTH", "ZEROFILL", "ZONE",
    ]

    static let completionPhrases = [
        "CHARACTER SET", "CROSS JOIN", "FOR SHARE", "FOR UPDATE", "FOREIGN KEY", "GROUP BY",
        "IF EXISTS", "IF NOT EXISTS", "INNER JOIN", "IS NOT NULL", "IS NULL", "LEFT JOIN",
        "LOCK IN SHARE MODE", "NATURAL JOIN", "NOT NULL", "ON DUPLICATE KEY UPDATE",
        "ORDER BY", "PRIMARY KEY", "RELEASE SAVEPOINT", "RENAME TO", "RIGHT JOIN",
        "START TRANSACTION", "UNION ALL", "WITH ROLLUP",
    ]

    static let keywords: [String] = {
        let phrasesByLeadingKeyword = Dictionary(
            grouping: completionPhrases
        ) { phrase in
            String(phrase.split(separator: " ", maxSplits: 1)[0])
        }
        var result: [String] = []
        result.reserveCapacity(mysqlKeywords.count + completionPhrases.count)
        var insertedPhrases: Set<String> = []

        for keyword in mysqlKeywords {
            result.append(keyword)
            guard let phrases = phrasesByLeadingKeyword[keyword] else {
                continue
            }
            result.append(contentsOf: phrases)
            insertedPhrases.formUnion(phrases)
        }
        result.append(contentsOf: completionPhrases.filter {
            !insertedPhrases.contains($0)
        })
        return result
    }()

    // Union of useful MySQL 5.7, 8.0, and 8.4 optimizer hint names.
    // The connected server remains authoritative for version support.
    static let optimizerHints = [
        "BKA", "BNL", "DERIVED_CONDITION_PUSHDOWN", "GROUP_INDEX",
        "HASH_JOIN", "INDEX", "INDEX_MERGE", "JOIN_FIXED_ORDER",
        "JOIN_INDEX", "JOIN_ORDER", "JOIN_PREFIX", "JOIN_SUFFIX",
        "MAX_EXECUTION_TIME", "MERGE", "MRR", "NO_BKA", "NO_BNL",
        "NO_DERIVED_CONDITION_PUSHDOWN", "NO_GROUP_INDEX",
        "NO_HASH_JOIN", "NO_ICP", "NO_INDEX", "NO_INDEX_MERGE",
        "NO_JOIN_INDEX", "NO_MERGE", "NO_MRR", "NO_ORDER_INDEX",
        "NO_RANGE_OPTIMIZATION", "NO_SEMIJOIN", "NO_SKIP_SCAN",
        "ORDER_INDEX", "QB_NAME", "RESOURCE_GROUP", "SEMIJOIN",
        "SET_VAR", "SKIP_SCAN", "SUBQUERY", "USE_INDEX_EXTENSIONS",
    ]

    static let statementKeywords = [
        "WITH", "SELECT", "SHOW", "DESCRIBE", "DESC", "EXPLAIN",
        "ANALYZE", "OPTIMIZE", "CHECK", "REPAIR", "USE", "DO", "CALL",
        "LOAD", "HANDLER", "INSERT", "REPLACE", "UPDATE", "DELETE",
        "CREATE", "ALTER", "DROP", "TRUNCATE", "RENAME", "GRANT",
        "REVOKE", "PREPARE", "EXECUTE", "DEALLOCATE", "SET", "BEGIN",
        "START TRANSACTION", "COMMIT", "ROLLBACK", "SAVEPOINT",
        "RELEASE SAVEPOINT", "LOCK", "UNLOCK", "FLUSH", "RESET", "KILL",
    ]

    static let insertKeywords = ["INTO"]

    static let insertBodyKeywords = ["VALUES", "SELECT"]

    static let updateBodyKeywords = ["SET"]

    static let assignmentKeywords = ["WHERE", "ORDER BY", "LIMIT"]

    static let deleteKeywords = ["FROM"]

    static let ddlObjectTypeKeywords = [
        "TABLE", "VIEW", "DATABASE", "SCHEMA", "INDEX", "EVENT", "FUNCTION",
        "PROCEDURE", "TRIGGER", "USER", "ROLE", "TABLESPACE", "SERVER",
    ]

    static let ddlObjectTypeKeywordsWithTemporary = ["TEMPORARY"]
        + ddlObjectTypeKeywords

    static let ddlBodyKeywords = [
        "ADD", "COLUMN", "MODIFY", "CHANGE", "DROP", "RENAME TO",
        "IF EXISTS", "IF NOT EXISTS",
    ]

    static let selectListKeywords = [
        "INTO", "FROM", "AS", "ALL", "DISTINCT", "DISTINCTROW", "CASE",
        "EXISTS",
    ]

    static let postRelationKeywords = [
        "JOIN", "LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "CROSS JOIN",
        "NATURAL JOIN", "STRAIGHT_JOIN", "WHERE", "GROUP BY", "HAVING",
        "ORDER BY", "LIMIT", "UNION", "UNION ALL", "FOR UPDATE", "FOR SHARE",
        "LOCK IN SHARE MODE",
    ]

    static let postJoinRelationKeywords = ["ON"] + postRelationKeywords

    static let setOperationKeywords = [
        "UNION", "UNION ALL", "INTERSECT", "EXCEPT",
    ]

    static let predicateKeywords = [
        "AND", "OR", "XOR", "NOT", "IN", "EXISTS", "ANY", "ALL",
        "IS NULL", "IS NOT NULL", "LIKE", "REGEXP", "RLIKE", "BETWEEN",
        "CASE", "WHEN", "THEN", "ELSE", "END",
    ]

    static let groupingKeywords = [
        "HAVING", "WITH ROLLUP", "ORDER BY", "LIMIT", "WINDOW",
    ]

    static let orderingKeywords = ["ASC", "DESC", "LIMIT"]

    // MySQL 5.7, 8.0, and 8.4 union. Completion is intentionally
    // version-agnostic; the connected server decides whether a function is
    // available when the statement executes.
    static let builtInFunctions = [
        "ABS", "ACOS", "ADDDATE", "ADDTIME", "AES_DECRYPT", "AES_ENCRYPT",
        "ANY_VALUE", "AREA", "ASBINARY", "ASCII", "ASIN", "ASTEXT",
        "ASYMMETRIC_DECRYPT",
        "ASYMMETRIC_DERIVE", "ASYMMETRIC_ENCRYPT", "ASYMMETRIC_SIGN",
        "ASYMMETRIC_VERIFY", "ATAN", "ATAN2", "AVG",
        "BENCHMARK", "BIN", "BINARY", "BIN_TO_UUID", "BIT_AND", "BIT_COUNT",
        "BIT_LENGTH", "BIT_OR", "BIT_XOR", "BUFFER",
        "CAN_ACCESS_COLUMN", "CAN_ACCESS_DATABASE", "CAN_ACCESS_TABLE",
        "CAN_ACCESS_USER", "CAN_ACCESS_VIEW", "CAST", "CEIL", "CEILING",
        "CHAR", "CHAR_LENGTH", "CHARACTER_LENGTH", "CHARSET", "COALESCE",
        "COERCIBILITY", "COLLATION", "COMPRESS", "CONCAT", "CONCAT_WS",
        "CONNECTION_ID", "CONV", "CONVERT", "CONVERT_TZ", "COS", "COT",
        "COUNT", "CRC32", "CREATE_ASYMMETRIC_PRIV_KEY",
        "CREATE_ASYMMETRIC_PUB_KEY", "CREATE_DH_PARAMETERS",
        "CREATE_DIGEST", "CUME_DIST", "CURDATE", "CURRENT_DATE",
        "CURRENT_ROLE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER",
        "CURTIME",
        "DATABASE", "DATE", "DATEDIFF", "DATE_ADD", "DATE_FORMAT", "DATE_SUB",
        "DAY", "DAYNAME", "DAYOFMONTH", "DAYOFWEEK", "DAYOFYEAR", "DECODE",
        "DEFAULT", "DEGREES", "DENSE_RANK", "DES_DECRYPT", "DES_ENCRYPT",
        "ELT", "ENCODE", "ENCRYPT", "EXP", "EXPORT_SET", "EXTRACT",
        "EXTRACTVALUE",
        "FIELD", "FIND_IN_SET", "FIRST_VALUE", "FLOOR", "FORMAT", "FORMAT_BYTES",
        "FORMAT_PICO_TIME", "FOUND_ROWS", "FROM_BASE64", "FROM_DAYS",
        "FROM_UNIXTIME",
        "GEOMCOLLECTION", "GEOMCOLLFROMTEXT", "GEOMCOLLFROMWKB",
        "GEOMETRYCOLLECTION", "GEOMETRYCOLLECTIONFROMTEXT",
        "GEOMETRYCOLLECTIONFROMWKB", "GEOMETRYFROMTEXT", "GEOMETRYFROMWKB",
        "GEOMETRYN", "GEOMETRYTYPE", "GEOMFROMTEXT", "GEOMFROMWKB",
        "GET_FORMAT", "GET_LOCK",
        "GREATEST", "GROUP_CONCAT", "GROUPING", "GTID_SUBSET",
        "GTID_SUBTRACT",
        "HEX", "HOUR",
        "ICU_VERSION", "IF", "IFNULL", "INET6_ATON", "INET6_NTOA", "INET_ATON",
        "INET_NTOA", "INSERT", "INSTR", "INTERNAL_AUTO_INCREMENT",
        "INTERNAL_AVG_ROW_LENGTH", "INTERNAL_CHECK_TIME",
        "INTERNAL_CHECKSUM", "INTERNAL_DATA_FREE", "INTERNAL_DATA_LENGTH",
        "INTERNAL_DD_CHAR_LENGTH", "INTERNAL_GET_COMMENT_OR_ERROR",
        "INTERNAL_GET_ENABLED_ROLE_JSON", "INTERNAL_GET_HOSTNAME",
        "INTERNAL_GET_USERNAME", "INTERNAL_INDEX_COLUMN_CARDINALITY",
        "INTERNAL_INDEX_LENGTH", "INTERNAL_IS_ENABLED_ROLE",
        "INTERNAL_IS_MANDATORY_ROLE", "INTERNAL_KEYS_DISABLED",
        "INTERNAL_MAX_DATA_LENGTH", "INTERNAL_TABLE_ROWS",
        "INTERNAL_UPDATE_TIME", "IS_FREE_LOCK", "IS_IPV4", "IS_IPV4_COMPAT",
        "IS_IPV4_MAPPED", "IS_IPV6", "ISNULL", "IS_USED_LOCK",
        "JSON_ARRAY", "JSON_ARRAYAGG", "JSON_ARRAY_APPEND", "JSON_ARRAY_INSERT",
        "JSON_CONTAINS", "JSON_CONTAINS_PATH", "JSON_DEPTH", "JSON_EXTRACT",
        "JSON_INSERT", "JSON_KEYS", "JSON_LENGTH", "JSON_MERGE",
        "JSON_MERGE_PATCH", "JSON_MERGE_PRESERVE", "JSON_OBJECT",
        "JSON_OBJECTAGG", "JSON_OVERLAPS", "JSON_PRETTY", "JSON_QUOTE",
        "JSON_REMOVE", "JSON_REPLACE", "JSON_SCHEMA_VALID",
        "JSON_SCHEMA_VALIDATION_REPORT", "JSON_SEARCH", "JSON_SET",
        "JSON_STORAGE_FREE", "JSON_STORAGE_SIZE", "JSON_TABLE", "JSON_TYPE",
        "JSON_UNQUOTE", "JSON_VALID", "JSON_VALUE",
        "LAG", "LAST_DAY", "LAST_INSERT_ID", "LAST_VALUE", "LCASE", "LEAD",
        "LEAST", "LEFT", "LENGTH", "LINESTRING", "LN", "LOAD_FILE", "LOCALTIME",
        "LOCALTIMESTAMP", "LOCATE", "LOG", "LOG10", "LOG2", "LOWER", "LPAD",
        "LTRIM",
        "MAKE_SET", "MAKEDATE", "MAKETIME", "MASTER_POS_WAIT", "MAX",
        "MBRCONTAINS", "MBRCOVEREDBY", "MBRCOVERS", "MBRDISJOINT",
        "MBREQUALS", "MBRINTERSECTS", "MBROVERLAPS", "MBRTOUCHES",
        "MBRWITHIN", "MD5", "MICROSECOND", "MID", "MIN", "MINUTE", "MOD",
        "MONTH", "MONTHNAME",
        "MULTILINESTRING", "MULTIPOINT", "MULTIPOLYGON",
        "NAME_CONST", "NOW", "NTH_VALUE", "NTILE", "NULLIF",
        "OCT", "OCTET_LENGTH", "OLD_PASSWORD", "ORD",
        "PASSWORD", "PERCENT_RANK", "PERIOD_ADD", "PERIOD_DIFF", "PI", "POINT",
        "POLYGON",
        "POSITION", "POW", "POWER", "PS_CURRENT_THREAD_ID", "PS_THREAD_ID",
        "QUARTER", "QUOTE",
        "RADIANS", "RAND", "RANDOM_BYTES", "RANK", "REGEXP_INSTR",
        "REGEXP_LIKE", "REGEXP_REPLACE", "REGEXP_SUBSTR", "RELEASE_ALL_LOCKS",
        "RELEASE_LOCK", "REPEAT", "REPLACE", "REVERSE", "RIGHT", "ROLES_GRAPHML",
        "ROUND", "ROW_COUNT", "ROW_NUMBER", "RPAD", "RTRIM",
        "SCHEMA", "SEC_TO_TIME", "SECOND", "SESSION_USER", "SHA", "SHA1",
        "SHA2", "SIGN", "SIN", "SLEEP", "SOUNDEX", "SOURCE_POS_WAIT", "SPACE",
        "SQRT", "ST_AREA", "ST_ASBINARY", "ST_ASGEOJSON", "ST_ASTEXT",
        "ST_ASWKB", "ST_ASWKT", "ST_BUFFER", "ST_BUFFER_STRATEGY",
        "ST_CENTROID", "ST_COLLECT", "ST_CONTAINS", "ST_CONVEXHULL",
        "ST_CROSSES",
        "ST_DIFFERENCE", "ST_DIMENSION", "ST_DISJOINT", "ST_DISTANCE",
        "ST_DISTANCE_SPHERE", "ST_ENDPOINT", "ST_ENVELOPE", "ST_EQUALS",
        "ST_EXTERIORRING", "ST_FRECHETDISTANCE", "ST_GEOHASH",
        "ST_GEOMCOLLFROMTEXT", "ST_GEOMCOLLFROMTXT", "ST_GEOMCOLLFROMWKB",
        "ST_GEOMETRYCOLLECTIONFROMTEXT", "ST_GEOMETRYCOLLECTIONFROMWKB",
        "ST_GEOMETRYFROMTEXT", "ST_GEOMETRYFROMWKB", "ST_GEOMETRYN",
        "ST_GEOMETRYTYPE", "ST_GEOMFROMGEOJSON", "ST_GEOMFROMTEXT",
        "ST_GEOMFROMWKB", "ST_HAUSDORFFDISTANCE", "ST_INTERIORRINGN",
        "ST_INTERSECTION", "ST_INTERSECTS", "ST_ISCLOSED", "ST_ISEMPTY",
        "ST_ISSIMPLE", "ST_ISVALID", "ST_LATFROMGEOHASH", "ST_LATITUDE",
        "ST_LENGTH", "ST_LINEFROMTEXT", "ST_LINEFROMWKB",
        "ST_LINEINTERPOLATEPOINT", "ST_LINEINTERPOLATEPOINTS",
        "ST_LINESTRINGFROMTEXT", "ST_LINESTRINGFROMWKB",
        "ST_LONGFROMGEOHASH", "ST_LONGITUDE", "ST_MAKEENVELOPE",
        "ST_MLINEFROMTEXT", "ST_MLINEFROMWKB", "ST_MPOINTFROMTEXT",
        "ST_MPOINTFROMWKB", "ST_MPOLYFROMTEXT", "ST_MPOLYFROMWKB",
        "ST_MULTILINESTRINGFROMTEXT", "ST_MULTILINESTRINGFROMWKB",
        "ST_MULTIPOINTFROMTEXT", "ST_MULTIPOINTFROMWKB",
        "ST_MULTIPOLYGONFROMTEXT", "ST_MULTIPOLYGONFROMWKB", "ST_NUMGEOMETRIES",
        "ST_NUMINTERIORRING", "ST_NUMINTERIORRINGS", "ST_NUMPOINTS",
        "ST_OVERLAPS", "ST_POINTATDISTANCE", "ST_POINTFROMGEOHASH",
        "ST_POINTFROMTEXT", "ST_POINTFROMWKB", "ST_POINTN", "ST_POLYFROMTEXT",
        "ST_POLYFROMWKB",
        "ST_POLYGONFROMTEXT", "ST_POLYGONFROMWKB", "ST_SIMPLIFY",
        "ST_SRID", "ST_STARTPOINT", "ST_SWAPXY", "ST_SYMDIFFERENCE",
        "ST_TOUCHES", "ST_TRANSFORM", "ST_UNION", "ST_VALIDATE", "ST_WITHIN",
        "ST_X", "ST_Y", "STATEMENT_DIGEST", "STATEMENT_DIGEST_TEXT", "STD",
        "STDDEV", "STDDEV_POP", "STDDEV_SAMP", "STRCMP", "STR_TO_DATE",
        "SUBDATE", "SUBSTR", "SUBSTRING", "SUBSTRING_INDEX", "SUBTIME", "SUM",
        "SYSDATE", "SYSTEM_USER",
        "TAN", "TIME", "TIMEDIFF", "TIMESTAMP", "TIMESTAMPADD",
        "TIMESTAMPDIFF", "TIME_FORMAT", "TIME_TO_SEC", "TO_BASE64", "TO_DAYS",
        "TO_SECONDS", "TRIM", "TRUNCATE",
        "UCASE", "UNCOMPRESS", "UNCOMPRESSED_LENGTH", "UNHEX", "UNIX_TIMESTAMP",
        "UPDATEXML", "UPPER", "USER", "UTC_DATE", "UTC_TIME", "UTC_TIMESTAMP",
        "UUID",
        "UUID_SHORT", "UUID_TO_BIN",
        "VALIDATE_PASSWORD_STRENGTH", "VALUES", "VARIANCE", "VAR_POP", "VAR_SAMP",
        "VERSION",
        "WAIT_FOR_EXECUTED_GTID_SET", "WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS",
        "WEEK", "WEEKDAY", "WEEKOFYEAR", "WEIGHT_STRING",
        "YEAR", "YEARWEEK",
    ]

    static let builtInFunctionSet = Set(builtInFunctions)
}
